name: Build and deploy Node.js app to Azure Web App - resume-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: |
          npm install

      - name: npm build
        run: |
          CI=false npm run build  # Set CI=false to prevent warnings from failing the build
          ls -R build

      - name: Zip artifact for deployment
        run: zip -r release.zip build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Check artifact contents
        run: ls -R

      - name: Unzip artifact for deployment
        run: unzip release.zip -d build

      - name: List files after unzip
        run: ls -R build

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Use the API Token here
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # This is automatically available in GitHub Actions
          action: "upload"
          app_location: "/"
          api_location: "api"  # Optional, use if you have an API folder
          output_location: "/build"  # Path to your build folder
