name: Deploy React to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pulls latest code from GitHub

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change to match your Node.js version

      - name: Install Dependencies
        run: npm install  # Installs dependencies

      - name: Build React App
        run: npm run build  # Builds the project

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Change if your React project is inside a folder
          output_location: "dist"  # Change to "build" if using Create React App
